# This configuration file should be kept secret
# as it includes sensitive information such as passwords.
# Please 'chmod 600' this configuration file.

dbfqdn: "localhost"
dbport: "5432"
dbuser: "gocron"
dbpass: "password"
dbdatabase: "gocron"
smtpserver: "smtp.gmail.com"
smtpport: "587"
smtpaddress: ""
smtppassword: ""
Interval: 60
SlackHookUrl: ""
SlackChannel: ""
PreferSlack: true
